name: Test AWS OIDC Setup

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
  test-aws-oidc:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::611182197776:role/githubaction-role

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.16.0" 

      - name: Terraform init
        run: terraform init & terraform plan -out plan.out

      # - name: Terraform apply
      #   run: terraform apply plan.out