name: AWS OIDCS Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  TF_VERSION: "1.16.0"
  TF_WORKING_DIR: terraform-aws

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Scan & Validate
        uses: ./.github/actions/terraform-scan
        with:
          terraform-version: ${{ env.TF_VERSION }}
          working-directory: ${{ env.TF_WORKING_DIR }}

  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform setup
        uses: ./.github/actions/terraform-aws
        with:
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::611182197776:role/githubaction-role
          terraform-version: ${{ env.TF_VERSION }}
          working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out plan.out

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}/plan.out

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform setup
        uses: ./.github/actions/terraform-aws
        with:
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::611182197776:role/githubaction-role
          terraform-version: ${{ env.TF_VERSION }}
          working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}

      - name: Terraform apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply plan.out
